version: "3"

services:
  app: # services: any name, this case will name it app
    build:
      context: . #current dir
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app #map app dir to the app dir in our docker image
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"